Use as a microservice
bilby91/ganban pull request #4
Opened 2016-11-21 08:14 UTC by patelnav

I work on many AppEngine projects, one interesting way to use Ganban would be to deploy it into your AppEngine environment as a [microservice](https://cloud.google.com/appengine/docs/python/microservices-on-app-engine), alongside the project you're working on

An important things to consider in this case is to make sure you're using [namespaces](https://cloud.google.com/appengine/docs/python/multitenancy/multitenancy). This way you don't have any overlap on the application you're working on when Ganban is running in parallel.

2016-11-21 16:32 UTC, patelnav commented
Another point! If you've already deployed into the default namespace, and want to transfer over to your brand new one. You can:
1) Export entities using the [Datastore Admin](https://console.cloud.google.com/datastore/settings)
2) Re-import them into the target namespace (the service name)

2016-11-21 20:19 UTC, patelnav commented
Note, if you don't set a "service" value, or keep the value to "default", there is no change in what namespace is used

2016-11-22 18:08 UTC, bilby91 commented
@patelnav Will look at your PRs today or tomorrow morning!

2016-11-22 18:24 UTC, bilby91 requested changes

2016-11-22 18:24 UTC, bilby91 commented on app.yaml
> +    # login: admin
Why is this commented ? If it's not necessary we can remove it.

2016-11-22 19:50 UTC, patelnav commented on app.yaml
> +    # login: admin
I've left it in there as a reminder that this is an option to restrict to admin, but commented it so the default behaviour is maintained. 

A completely publicly open board is not really practical. IMO it makes sense to restrict this to admin. Are there any boards that are actively being used right now?

2016-12-01 22:09 UTC, bilby91 approved these changes

2016-12-01 22:10 UTC, bilby91 commented
@patelnav Please resolve conflicts !

Are you interested in becoming maintainer of @ganban ?

2016-12-02 17:48 UTC, patelnav commented
Hmm. Not sure what the conflict was. Rebased off of master and pushed again. Should be good to go!

2016-12-02 17:55 UTC, patelnav commented
@bilby91: sure!

2016-12-02 18:17 UTC, merged